stages:
  - test

test_project:
  stage: test
  script:
    - set -o pipefail && xcodebuild clean -workspace Box-Office-Movies.xcworkspace -scheme Box-Office-Movies | xcpretty
    - set -o pipefail && xcodebuild test -workspace Box-Office-Movies.xcworkspace -scheme Box-Office-Movies_Development -derivedDataPath Build/ -destination 'platform=iOS Simulator,name=iPhone 8,OS=13.3' | xcpretty
    - set -o pipefail && echo "test_coverage=`xcrun xccov view --report Build/Logs/Test/*.xcresult | grep 'Box-Office-Movies.app' | head -1 | perl -pe 's/.+?(\d+\.\d+%).+/\1/'`"
  tags:
    - iOS-13.3
    - Xcode-11

test_core:
  stage: test
  script:
    - set -o pipefail && xcodebuild clean -workspace Box-Office-Movies.xcworkspace -scheme Box-Office-Movies-Core | xcpretty
    - set -o pipefail && xcodebuild test -workspace Box-Office-Movies.xcworkspace -scheme Box-Office-Movies-Core -derivedDataPath Build/ -destination 'platform=iOS Simulator,name=iPhone 8,OS=13.3' | xcpretty
    - set -o pipefail && echo "test_coverage=`xcrun xccov view --report Build/Logs/Test/*.xcresult | grep 'Box_Office_Movies_Core.framework' | head -1 | perl -pe 's/.+?(\d+\.\d+%).+/\1/'`"
  tags:
  - iOS-13.3
  - Xcode-11
