stages:
  - test

test_project:
  stage: test
  script:
    - set -o pipefail && xcodebuild clean -scheme Box-Office-Movies_CI | xcpretty
    - set -o pipefail && xcodebuild test -scheme Box-Office-Movies_CI -derivedDataPath Build/ -destination 'platform=iOS Simulator,name=iPhone 8,OS=13.4.1' | xcpretty
    - set -o pipefail && echo "test_coverage=`xcrun xccov view --report Build/Logs/Test/Test-Box-Office-Movies_CI-*.xcresult | grep 'Boxotop.app' | head -1 | perl -pe 's/.+?(\d+\.\d+%).+/\1/'`"
  tags:
    - iOS-13
    - Xcode-11

test_core:
  stage: test
  script:
    - set -o pipefail && xcodebuild clean -scheme Box-Office-Movies-Core_CI | xcpretty
    - set -o pipefail && xcodebuild test -scheme Box-Office-Movies-Core_CI -derivedDataPath Build/ -destination 'platform=iOS Simulator,name=iPhone 8,OS=13.4.1' | xcpretty
    - set -o pipefail && echo "test_coverage=`xcrun xccov view --report Build/Logs/Test/Test-Box-Office-Movies-Core_CI-*.xcresult | grep 'Box_Office_Movies_Core.framework' | head -1 | perl -pe 's/.+?(\d+\.\d+%).+/\1/'`"
  tags:
    - iOS-13
    - Xcode-11
  only:
    changes:
      - Box-Office-Movies-Core/**/*
