disabled_rules: # rule identifiers to exclude from running
  - line_length
  - nesting
  - trailing_whitespace
  - type_name
  - identifier_name
  
excluded: # paths to ignore during linting. Takes precedence over `included`.
  # - NumbersApplicationTests