workspace "../Box-Office-Movies.xcworkspace"

devices([
  "iPhone 11 Pro"
])

languages([
  "fr-FR"
])

clear_previous_screenshots(true)

#
reinstall_app(true)
app_identifier(fr.)

#
erase_simulator(true)
localize_simulator(true)
dark_mode(true)
